pipeline {
    agent any
    stages{
        stage ("Git Checkout"){
            steps{
                git branch: '', credentialsId: 'git credentials', url: 'https://github.com/SivaShravani/Project.git'
            }
        }
        stage("Maven Build"){
            steps{
                "mvn clean install"
            }
        }
        stage("Building image"){
            steps{
                sh "docker build -t project-repo/myapp:1.0 ."
        }
    }
}






